# Generated by Django 4.0.3 on 2022-03-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150, verbose_name='site name')),
                ('logo', models.ImageField(upload_to='settings/', verbose_name='logo')),
                ('phone', models.CharField(max_length=520, verbose_name='phone')),
                ('email', models.CharField(max_length=520, verbose_name='email')),
                ('address', models.CharField(max_length=520, verbose_name='address')),
                ('description', models.TextField(verbose_name='description')),
                ('fb_link', models.URLField(verbose_name='fb link')),
                ('twitter_link', models.URLField(verbose_name='twitter link')),
                ('instagram_link', models.URLField(verbose_name='instagram link')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settingss',
            },
        ),
    ]
